name: myHerd Build and Deployment
on:
  push
   workflow_dispatch:
     inputs:
       environment:
         description: 'Choose the deployment environment!'
         type: choice
         required: true
         default: "Test"
         options:
         - "Dev"
         - "UAT"
         - "Prod"
env:
  ENV_NAME: ${{ github.event.inputs.environment }}

permissions:
    id-token: write
    contents: read
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:     
      - name: Build
        run: |
          echo "build"

      - name: Push Build Artifact
        run: |
          echo "push"
  
  DevDeploy:
    name: deveopment env
    if: github.event.inputs.environment == 'Dev'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: thilees
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
      
      - name: Dev Deploy
        run: |
          echo "Dev Deploy"
  UatDeploy:
    name: UAT Deploy
    if: github.event.inputs.environment == 'UAT'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Uat Deploy
        run: |
          echo "UAT Deploy"
          
