---
name: Build and Pord-Deploy

on: 
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  StartRunner:  
    name: "Start Runner"
    runs-on: [ubuntu-latest]

    steps:      
      - name: "Starting Runner"
        shell: bash        
        run: |
          echo "Starting the runner..."
  Build:  
    name: "App Build"
    runs-on: [ubuntu-latest]
    needs: [StartRunner]

    steps:
      - name: "Building applicaiton"
        run: |    
          echo "Building the applicaiotn"
  PushingArtifact:        
    name: "Pushing Artifact"
    runs-on: [ubuntu-latest]
    needs: [Build]

    steps:
      - name: "Pushing Artifact"
        run: |
          echo "Pushing Artifact"
  
  DeployTest:        
    name: "Deploy to Test"
    runs-on: [ubuntu-latest]
    needs: [PushingArtifact]
    steps:
      - name: "Deploying"        
        run: |
          echo "Deploying"          
  
  UATApproval:        
    name: "UAT Approval"
    runs-on: [ubuntu-latest]
    needs: [DeployTest]
    environment: Prod
    steps:
      - name: "Deploying"        
        run: |
          echo "Deploying"
          
  DeployUAT:        
    name: "Deploy to UAT"
    runs-on: [ubuntu-latest]
    needs: [UATApproval]
    steps:
      - name: "Deploying"        
        run: |
          echo "Deploying"   
          
  ProdApproval:        
    name: "Prod Approval"
    runs-on: [ubuntu-latest]
    needs: [DeployUAT]
    environment: Prod
    steps:
      - name: "Deploying"        
        run: |
          echo "Deploying"
  
  DeployProd:        
    name: "Deploy to Prod"
    runs-on: [ubuntu-latest]
    needs: [ProdApproval]

    steps:
      - name: "Deploying"        
        run: |
          echo "Deploying"
          
  StopRunner:  
    name: "Stop Runner"
    runs-on: [ubuntu-latest]
    needs: [DeployProd]
    steps:      
      - name: "Stoping Runner"
        shell: bash        
        run: |
          echo "Stoping the runner..."
