name: myHerd Build and Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the deployment environment!'
        type: choice
        required: true
        default: "Test"
        options:
        - "Dev"
        - "UAT"
        - "Prod"

permissions:
    id-token: write
    contents: read
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Push Build Artifact
        run: |
          echo "build and push"  
          
  DevDeploy:
    name: Dev Deploy
    if: github.event.inputs.environment == 'Dev' || github.event.inputs.environment == 'Prod'
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Dev Deploy
        run: |
          echo "Dev Deploy"

  UATDeploy:
    name: UAT Deploy
    if: github.event.inputs.environment == 'UAT' || github.event.inputs.environment == 'Prod'
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Dev Deploy
        run: |
          echo "UAT deployment"
   
  ProdDeploy:
    name: Prod Deploy
    if: github.event.inputs.environment == 'Prod' || github.event.inputs.environment == 'Prod'
    runs-on: ubuntu-latest
    needs: [DevDeploy, UATDeploy]
    steps:
      - name: Dev Deploy
        run: |
          echo "Prod deployment"
