name: myHerd Build and Deployment
on:
   workflow_dispatch:
     inputs:
       environment:
         description: 'Choose the deployment environment!'
         type: choice
         required: true
         default: "Test"
         options:
         - "Dev"
         - "UAT"
         - "Prod"
env:
  ENV_NAME: "Test" #${{ github.event.inputs.environment }}

permissions:
    id-token: write
    contents: read
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:     
      - name: Build
        run: |
          echo "build"

      - name: Push Build Artifact
        run: |
          echo "push"
  DevDeploy:
    name: Dev Deploy
    if: github.event.inputs.environment == 'Dev' || github.event.inputs.environment == 'Prod'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Dev Deploy
        run: |
          echo "Dev Deploy"
  UatDeploy:
    name: UAT Deploy
    if: github.event.inputs.environment == 'UAT'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Uat Deploy
        run: |
          echo "UAT Deploy"
          
